### ISSUE TITLE
Status Page

### ISSUE THREAD

**Issue by Incrested** [Miku-Chan-Devs/Miku-Chan#42]
For Discord API and the Heroku Servers, we should have a status page indexed to "status.mikuchan.me" or "mikuchan.me/status". I've been looking at [CachetHQ/Cachet](https://github.com/CachetHQ/Cachet) and [Statuspage.io](https://statuspage.io). I'm going to find a nice looking one that still has security/functionality.

**Comment by ultraMLGcode** [comment]
Statuspage.io is a good one, I believe it’s what Discord uses.

**Comment by Incrested** [comment]
Yeah, I think Cachet or Staytus is better since their both OSS and free. Status page is 100$ p/ mo.

**Comment by Incrested** [comment]
Done: http://status.mikuchan.me
